name: Run Pytest on Specific File

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pytest numpy ase

      - name: Run tests for a specific file
        run: pytest eslib/classes/cube.py
